/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JFrames;

import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import Connection.DatabaseConnection;
import static JFrames.Objects.con;
import static JFrames.Objects.cst;
import static JFrames.Objects.pst;
import static JFrames.Objects.rs;

/**
 *
 * @author Joshua C. Magoliman
 */
public class JFrame_CreateAnotherAccount extends javax.swing.JFrame {

    /**
     * Creates new form JFrame_CreateAnotherAccount
     */
    public JFrame_CreateAnotherAccount() {
        initComponents();
        DatabaseConnection dbc = DatabaseConnection.getDatabaseConnection();
        con = dbc.getConnection();
        SetIcon();
        Reset();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel = new javax.swing.JPanel();
        btnBack = new javax.swing.JButton();
        txtUsername = new javax.swing.JTextField();
        lblUsername = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        chckbox_ShowPassword = new javax.swing.JCheckBox();
        txtPassword = new javax.swing.JPasswordField();
        lblSecretAnswer = new javax.swing.JLabel();
        cmbboxSecretQuestion = new javax.swing.JComboBox<>();
        lblSecretQuestion = new javax.swing.JLabel();
        txtSecretAnswer = new javax.swing.JPasswordField();
        chckbox_ShowSecretAnswer = new javax.swing.JCheckBox();
        btnRegister = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CREATE ANOTHER ACCOUNT ?");
        setResizable(false);

        jPanel.setBackground(new java.awt.Color(51, 0, 102));

        btnBack.setText("BACK");
        btnBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        txtUsername.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtUsername.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtUsername.setName(""); // NOI18N
        txtUsername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtUsernameKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUsernameKeyTyped(evt);
            }
        });

        lblUsername.setForeground(new java.awt.Color(255, 255, 255));
        lblUsername.setText("USERNAME");

        lblPassword.setForeground(new java.awt.Color(255, 255, 255));
        lblPassword.setText("PASSWORD");

        chckbox_ShowPassword.setBackground(new java.awt.Color(51, 0, 102));
        chckbox_ShowPassword.setForeground(new java.awt.Color(255, 255, 255));
        chckbox_ShowPassword.setText("Show Password");
        chckbox_ShowPassword.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        chckbox_ShowPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chckbox_ShowPasswordActionPerformed(evt);
            }
        });

        txtPassword.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtPassword.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPasswordKeyTyped(evt);
            }
        });

        lblSecretAnswer.setForeground(new java.awt.Color(255, 255, 255));
        lblSecretAnswer.setText("SECRET ANSWER");

        cmbboxSecretQuestion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "What is your favorite color?", "What is your contact number?", "When is your birthday?", "What is love for you?", "Where were you born ?", "What is the meaning of life?", "What is your gender?", "What is your civil status in life?", "What is your dream in life?", "What things that makes you happy?", "What things that makes you sad?", "What things that makes you mad?", "What is your job?", "What is your favorite song?", "What is your favorite band?", "What is your favorite singer?" }));

        lblSecretQuestion.setForeground(new java.awt.Color(255, 255, 255));
        lblSecretQuestion.setText("SECRET QUESTION");

        txtSecretAnswer.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtSecretAnswer.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtSecretAnswer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSecretAnswerKeyTyped(evt);
            }
        });

        chckbox_ShowSecretAnswer.setBackground(new java.awt.Color(51, 0, 102));
        chckbox_ShowSecretAnswer.setForeground(new java.awt.Color(255, 255, 255));
        chckbox_ShowSecretAnswer.setText("Show Secret Answer");
        chckbox_ShowSecretAnswer.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        chckbox_ShowSecretAnswer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chckbox_ShowSecretAnswerActionPerformed(evt);
            }
        });

        btnRegister.setText("REGISTER");
        btnRegister.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUsername)
                            .addComponent(lblPassword))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelLayout.createSequentialGroup()
                                .addComponent(chckbox_ShowPassword)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtPassword)
                            .addComponent(txtUsername)))
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblSecretAnswer)
                            .addComponent(lblSecretQuestion))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(chckbox_ShowSecretAnswer)
                            .addComponent(cmbboxSecretQuestion, 0, 243, Short.MAX_VALUE)
                            .addComponent(txtSecretAnswer))))
                .addContainerGap(94, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105))
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUsername))
                .addGap(18, 18, 18)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassword)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(chckbox_ShowPassword)
                .addGap(32, 32, 32)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSecretQuestion)
                    .addComponent(cmbboxSecretQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSecretAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSecretAnswer))
                .addGap(18, 18, 18)
                .addComponent(chckbox_ShowSecretAnswer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
 private void Reset() {
        txtUsername.setText("");
        txtPassword.setText("");
        cmbboxSecretQuestion.setSelectedItem("None");
        txtSecretAnswer.setText("");
        chckbox_ShowPassword.setSelected(false);
        chckbox_ShowSecretAnswer.setSelected(false);
        this.txtUsername.requestFocus();
    }
    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        if (btnBack.getText().equals("BACK")) {
            this.hide();
            new JFrame_Main().setVisible(true);
        } else {
            int P = JOptionPane.showConfirmDialog(null, " Are you sure want to cancel ?", "ATTENTION", JOptionPane.YES_NO_OPTION);
            if (P == JOptionPane.YES_OPTION) {
                this.hide();
                new JFrame_Main().setVisible(true);
            }
        }
    }//GEN-LAST:event_btnBackActionPerformed
    private void chckbox_ShowPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chckbox_ShowPasswordActionPerformed
        if (chckbox_ShowPassword.isSelected()) {
            txtPassword.setEchoChar((char) 0);
        } else {
            txtPassword.setEchoChar('*');
        }
        this.lblUsername.requestFocus();
    }//GEN-LAST:event_chckbox_ShowPasswordActionPerformed
    private void chckbox_ShowSecretAnswerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chckbox_ShowSecretAnswerActionPerformed
        if (chckbox_ShowSecretAnswer.isSelected()) {
            txtSecretAnswer.setEchoChar((char) 0);
        } else {
            txtSecretAnswer.setEchoChar('*');
        }
        this.lblUsername.requestFocus();
    }//GEN-LAST:event_chckbox_ShowSecretAnswerActionPerformed
    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        if (txtUsername.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "No Username Found !", "ATTENTIOM", JOptionPane.ERROR_MESSAGE);
            txtUsername.requestFocus();
        } else if (txtPassword.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "No Password Found!", "ATTENTION", JOptionPane.ERROR_MESSAGE);
            txtPassword.requestFocus();
        } else if (cmbboxSecretQuestion.getSelectedItem().equals("None")) {
            JOptionPane.showMessageDialog(this, "No Secret Question Found!", "ATTENTION", JOptionPane.ERROR_MESSAGE);
            cmbboxSecretQuestion.requestFocus();
        } else if (txtSecretAnswer.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "No Secret Answer Found!", "ATTENTION", JOptionPane.ERROR_MESSAGE);
            txtSecretAnswer.requestFocus();
        } else {
            try {
                pst = con.prepareStatement("SELECT * FROM tbl_Users WHERE Username=?");
                pst.setString(1, txtUsername.getText());
                rs = pst.executeQuery();
                if (rs.next()) {
                    JOptionPane.showMessageDialog(this, "This Username is already taken!", "ATTENTION", JOptionPane.ERROR_MESSAGE);
                } else {
                    CreatingAccount();
                }
            } catch (Exception ex) {
                System.out.println(ex);
            }
        }
    }//GEN-LAST:event_btnRegisterActionPerformed
    private void CreatingAccount() {
        try {
            cst = con.prepareCall("{call sp_InsertNewUser(?, ?, ?, ?)}");
            cst.setString("param_Username", txtUsername.getText());
            cst.setString("param_Password", txtPassword.getText());
            cst.setString("param_SecretQuestion", cmbboxSecretQuestion.getSelectedItem().toString());
            cst.setString("param_SecretAnswer", txtSecretAnswer.getText());
            if (cst.executeUpdate() == 1) {
                JOptionPane.showMessageDialog(this, "SUCCESSFULLY REGISTERED");
                Reset();
            }
        } catch (Exception ex) {
            System.out.println(ex);
        }
    }
    private void txtUsernameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsernameKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isAlphabetic(c) || Character.isDigit(c) || c == KeyEvent.VK_DELETE)) {
            evt.consume();
        }
        if (txtUsername.getText().length() >= 12) {
            evt.consume();
        }
    }//GEN-LAST:event_txtUsernameKeyTyped
    private void txtUsernameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsernameKeyReleased
        if (!txtUsername.getText().equals("")) {
            btnBack.setText("CANCEL");
        } else {
            btnBack.setText("BACK");
        }
    }//GEN-LAST:event_txtUsernameKeyReleased
    private void txtPasswordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPasswordKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isAlphabetic(c) || Character.isDigit(c) || c == KeyEvent.VK_DELETE)) {
            evt.consume();
        }
        if (txtPassword.getText().length() >= 12) {
            evt.consume();
        }
    }//GEN-LAST:event_txtPasswordKeyTyped
    private void txtSecretAnswerKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSecretAnswerKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isAlphabetic(c) || Character.isDigit(c) || Character.isWhitespace(c) || c == KeyEvent.VK_DELETE)) {
            evt.consume();
        }
        if (txtSecretAnswer.getText().length() >= 20) {
            evt.consume();
        }
    }//GEN-LAST:event_txtSecretAnswerKeyTyped
    private void SetIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("LOGOICON.png")));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame_CreateAnotherAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame_CreateAnotherAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame_CreateAnotherAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame_CreateAnotherAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame_CreateAnotherAccount().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRegister;
    private javax.swing.JCheckBox chckbox_ShowPassword;
    private javax.swing.JCheckBox chckbox_ShowSecretAnswer;
    private javax.swing.JComboBox<String> cmbboxSecretQuestion;
    private javax.swing.JPanel jPanel;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblSecretAnswer;
    private javax.swing.JLabel lblSecretQuestion;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JPasswordField txtSecretAnswer;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables

}
