/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JFrames;

import java.awt.ComponentOrientation;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import java.time.*;
import javax.swing.Box;

/**
 *
 * @author Joshua C. Magoliman
 */
public class JFrame_Main extends javax.swing.JFrame {

    /**
     * Creates new form JFrame_Main
     */
    public JFrame_Main() {
        initComponents();
        SetIcon();
        GetDateToday();
        GetTimeNow();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel = new javax.swing.JPanel();
        btnStudents = new javax.swing.JButton();
        lblTimeNow = new javax.swing.JLabel();
        lblDateToday = new javax.swing.JLabel();
        lblDayToday = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        jMenuBar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem_ChangePassword = new javax.swing.JMenuItem();
        jMenuItem_CreateAnotherAccount = new javax.swing.JMenuItem();
        jMenuItem_Logout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MAIN");
        setUndecorated(true);
        setResizable(false);

        jPanel.setBackground(new java.awt.Color(51, 0, 102));

        btnStudents.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnStudents.setText("STUDENTS");
        btnStudents.setBorderPainted(false);
        btnStudents.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnStudents.setDefaultCapable(false);
        btnStudents.setFocusPainted(false);
        btnStudents.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnStudents.setRequestFocusEnabled(false);
        btnStudents.setSelected(true);
        btnStudents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentsActionPerformed(evt);
            }
        });

        lblTimeNow.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblTimeNow.setForeground(new java.awt.Color(255, 255, 255));
        lblTimeNow.setText("TIME");

        lblDateToday.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblDateToday.setForeground(new java.awt.Color(255, 255, 255));
        lblDateToday.setText("DATE");

        lblDayToday.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblDayToday.setForeground(new java.awt.Color(255, 255, 255));
        lblDayToday.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblDayToday.setText("DAY");

        lblTitle.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("SIMPLE CRUD IN JAVA AND MYSQL");

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(lblDateToday)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblDayToday)
                .addGap(129, 129, 129)
                .addComponent(lblTimeNow)
                .addGap(64, 64, 64))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                .addContainerGap(299, Short.MAX_VALUE)
                .addComponent(btnStudents, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(273, 273, 273))
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(lblTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addComponent(btnStudents, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(132, 132, 132)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDateToday)
                    .addComponent(lblDayToday)
                    .addComponent(lblTimeNow))
                .addGap(51, 51, 51))
        );

        jMenuBar.setOpaque(false);
        jMenuBar.setSelectionModel(null);
        jMenuBar.add(Box.createHorizontalGlue());
        jMenuBar.add(jMenu1);

        jMenu1.setBorder(null);
        jMenu1.setText("SETTINGS");
        jMenu1.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        jMenu1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jMenu1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jMenuItem_ChangePassword.setText("Change Password");
        jMenuItem_ChangePassword.setComponentOrientation(ComponentOrientation.LEFT_TO_RIGHT);
        jMenuItem_ChangePassword.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem_ChangePassword.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jMenuItem_ChangePassword.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jMenuItem_ChangePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_ChangePasswordActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem_ChangePassword);

        jMenuItem_CreateAnotherAccount.setText("Create Another Account");
        jMenuItem_CreateAnotherAccount.setComponentOrientation(ComponentOrientation.LEFT_TO_RIGHT);
        jMenuItem_CreateAnotherAccount.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem_CreateAnotherAccount.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jMenuItem_CreateAnotherAccount.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jMenuItem_CreateAnotherAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_CreateAnotherAccountActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem_CreateAnotherAccount);

        jMenuItem_Logout.setText("Log-out");
        jMenuBar.setComponentOrientation(ComponentOrientation.LEFT_TO_RIGHT);
        jMenuItem_Logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem_Logout.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jMenuItem_Logout.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jMenuItem_Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_LogoutActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem_Logout);

        jMenuBar.add(jMenu1);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private void GetDateToday() {
        Date d = new Date();
        SimpleDateFormat s = new SimpleDateFormat("MMMM dd, yyyy");
        lblDateToday.setText(s.format(d));
    }

    private void GetTimeNow() {
        new Timer(0, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date d = new Date();
                SimpleDateFormat s = new SimpleDateFormat("hh:mm:ss a");
                lblTimeNow.setText(s.format(d));
                String GetDateToday = LocalDateTime.now().getDayOfWeek().toString();
                String Converting = GetDateToday.toLowerCase();
                String Output = Converting.substring(0, 1).toUpperCase() + Converting.substring(1);
                lblDayToday.setText(Output);
            }
        }).start();
    }
    private void btnStudentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentsActionPerformed
        this.hide();
        JFrame_Students nextForm = new JFrame_Students();
        nextForm.show();
    }//GEN-LAST:event_btnStudentsActionPerformed
    private void jMenuItem_LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_LogoutActionPerformed
        try {
            int P = JOptionPane.showConfirmDialog(null, " Are you sure want to log-out ?", "ATTENTION", JOptionPane.YES_NO_OPTION);
            if (P == JOptionPane.YES_OPTION) {
                this.hide();
                JFrame_Login nextForm = new JFrame_Login();
                nextForm.show();
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex);
        }
    }//GEN-LAST:event_jMenuItem_LogoutActionPerformed
    private void jMenuItem_CreateAnotherAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_CreateAnotherAccountActionPerformed
        this.hide();
        JFrame_CreateAnotherAccount nextForm = new JFrame_CreateAnotherAccount();
        nextForm.show();
    }//GEN-LAST:event_jMenuItem_CreateAnotherAccountActionPerformed
    private void jMenuItem_ChangePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_ChangePasswordActionPerformed
        this.hide();
        JFrame_ChangePassword nextForm = new JFrame_ChangePassword();
        nextForm.show();
    }//GEN-LAST:event_jMenuItem_ChangePasswordActionPerformed
    private void SetIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("LOGOICON.png")));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame_Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnStudents;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenuItem jMenuItem_ChangePassword;
    private javax.swing.JMenuItem jMenuItem_CreateAnotherAccount;
    private javax.swing.JMenuItem jMenuItem_Logout;
    private javax.swing.JPanel jPanel;
    private javax.swing.JLabel lblDateToday;
    private javax.swing.JLabel lblDayToday;
    private javax.swing.JLabel lblTimeNow;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
